




export const productList = () => {
   return [

      'Aluminum Foil',
      // 'Bags',
      'Coffee Filters',
      'Cups',
      'Garbage Bags',
      'Napkins',
      'Paper Towels',
      'Plastic Wrap',
      'Plates',
      'Tissues',
      'Toilet Paper',
      'Utensils',
      'Wax Paper',
      'Water',
      'Juice',
      'Soda',
      'Sports Drinks',
      'Coffee',
      'Tea',
      'Bitters',  //


      'Deodorant',
      'Floss',
      'Hair Spray',
      'Lip Balm',
      'Lotion',
      'Makeup',
      'Mouthwash',
      // 'Pain Relievers',
      'Razor Blades',
      'Shampoo',
      'Shaving Cream',
      'Soap',
      'Sunscreen',
      'Toothbrush',
      'Toothpaste',
      'Batteries',
      'Bleach',
      'Charcoal',
      'Detergent',
      'Dish Soap',
      // 'Dishwasher Soap',
      'Fabric Softener',
      // 'Glass Cleaner',



      // 'Light Bulbs',
      // 'Sponges',
      // 'Vacuum Bags',
      // 'Milk',
      // 'Chocolate',
      // 'Biscuits',
      // 'Ice Cream',
      // 'Lasagna',
      // 'Pie',
      // 'Pizza',
      // 'Yogurt',
      // 'Bagels',
      // 'Bread',
      // 'Cake',
      // 'Cookies',
      // 'Dinner Rolls',
      // 'Donuts',
      // 'French Bread',
      // 'Hamburger Buns',
      // 'Hot Dog Buns',
      // 'Muffins',
      // 'Pastries',
      // 'Pita Bread',
      // 'Tortillas',
      // 'Apples',
      // 'Avocados',
      // 'Bananas',
      // 'Berries',
      // 'Broccoli',
      // 'Carrots',
      // 'Celery',
      // 'Cucumbers',
      // 'Garlic',
      // 'Grapefruit',
      // 'Grapes',
      // 'Lemons/Limes',
      // 'Lettuce',
      // 'Melons',
      // 'Mushrooms',
      // 'Onions',
      // 'Oranges',
      'Peppers',
      'Potatoes',
      // 'Squash/Zucchini',
      // 'Tomatoes',
      // 'Pumpkin leaves',
      // 'Garden egg',
      // 'Garden Egg leaves',
      'Ijebu Garri',
      // 'Rice',
      // 'Beans',
      // 'Salt',
      // 'Maggi',
      // 'Knor',
      // 'Tumeric',
      // 'Curry',
      // 'Rosemary',
      // 'Thyme',
      // 'Honey',
      // 'Jam / Jelly',
      // 'Ketchup',
      // 'Mayonnaise',
      // 'Mustard',
      // 'Peanut Butter',
      // 'Pickles',
      // 'Salad Dressing cream',
      // 'Salsa',
      // 'Applesauce',
      // 'Beans',
      // 'Chili',
      // 'Fruits',
      // 'Mushrooms',
      // 'Olives',
      // 'Soup',
      // 'Tomato Sauce',
      // 'Tuna',
      // 'Desserts',
      // 'Dinners',
      // 'Fish',
      // 'Fruits',
      // 'Ice',
      // 'Ice Pops',
      // 'Vegetables',
      // 'Waffles',
      // 'Cookie Dough',
      // 'Butter',
      // 'Cheese',
      // 'Cream Cheese',
      // 'Dips',
      // 'Eggs',
      // 'Half & Half',
      // 'Milk',
      // 'Whip Cream',
      // 'Baking Powder',
      // 'Baking Soda',
      // 'Bread Crumbs',
      // 'Brownie Mix',
      // 'Cake Mix',
      // 'Canned Milk',
      // 'Chocolate Chips',
      // 'Cocoa',
      // 'Cornmeal',
      // 'Cornstarch',
      // 'Flour',
      // 'Food Coloring',
      // 'Frosting',
      // 'Muffin Mix',
      // 'Oatmeal',
      // 'Pie Crust',
      // 'Shortening',
      // 'Sugar (brown)',
      // 'Sugar (powder)',
      // 'Sugar (white)',
      // 'Vanilla',
      // 'Yeast',
      // 'Bacon',
      // 'Beef / Steak',
      // 'Chicken',
      // 'Deli Meat',
      // 'Fish',
      // 'Ground Beef',
      // 'Ham',
      // 'Pork',
      // 'Sausage',
      // 'Turkey',
      // 'Yam Flour',
      'Potato Flour',
      'Plantain Flour',
      // 'Cassava Flour',
      'Vegetable Oil',
      'Olive Oil',
      'BBQ Sauce',
      'Hot Sauce',
      'Spaghetti Sauce',
      'Palm Oil',
      'Ofor',
      'Achi',
      'Ogbono',
      'Yam',
      'Potato',
      'Cassava',



      'Dried Okazi',
      'Blended Okazi',
      'Dried Ngolo (Prewinkles)',
      'Dried Isam  (Prewinkles)',
      'Dried Bitterleaf',
      'Cashew nut',
      'Coconut Chips',
      'Groundnuts',
      'Aki na Ukwa',
      'Dried Oha',
      'Dried Uziza',
      'Dried/Blended Uziza seed',
      'Egusi',
      'Okpa Flour',
      'Ukpo (ABACHI)',
      'Dried Utazi',
      'Azuma (AKIDI)',
      'STOCKFISH',
      // 'COD Head',
      'Cameroon Pepper',
      'Red Pepper',
      'Dried Abacha',
      // 'African Swallow',
      'Dried Ehure',
      'Dried Scent Leaf',
      'Atama Leave',
      // 'Blended Fish',
      'Blended Crayfish',
      'Blended Prawns',
      'Beans Powder',
      // 'Edible Starch',
      'Ogiri Igbo',
      'Pap (Akamu)',
      'Dried Fish',
      'Amala',
      'Yellow Garri',
      'Honey Beans',
      'Peeled Beans',
      'Black eyed Beans',
      'White Corn',
      'Uda',
      'Aligator Pepper',
      'Ground Ogbono',
      'Ugba seeds (African oil bean seeds)',
      'Calabash Nutmeg (Ehuru )',
      'Melon seeds (Egusi )',
      'Yam flour (Elubo)'

   ]

}