const images = {
  logo: require("./techluchlogow-min.png").default,
  logo2: require("./techluchlogosingle-min.png").default,
  landingImg: require("./group4-min.png").default,
  business: require("./group12-min.png").default,
  legal: require("./group10-min.png").default,
  coins: require("./coins-min.png").default,
  cash: require("./attach_money-min.png").default,
  order: require("./group31-min.png").default,
  investor: require("./group29-min.png").default,
  dream: require("./group28-min.png").default,
  rectangle: require("./group47-min.png").default,
  rectangle2: require("./group46-min.png").default,
  rectangle3: require("./group48-min.png").default,
  partner1: require("./partnerone.jpeg").default,
  partner2: require("./partnertwo.jpeg").default,
  partner3: require("./partnerthree.jpeg").default,
  partner4: require("./partnerfour.jpeg").default,
  partner5: require("./master.jpeg").default,
  partner6: require("./visa.jpeg").default,
  partner7: require("./paypal.jpeg").default,
  form1: require("./group471-min.png").default,
  form2: require("./group461-min.png").default,
  form3: require("./group481-min.png").default,
  upload: require("./upload-min.png").default,
  phoneIcon: require("./phonecall-min.png").default,
  mailIcon: require("./message-min.png").default,
  whatsapp: require("./whatsapp-min.png").default,
  investorPics: require("./businessman-amico.png").default,
  good: require("./check-mark-min.png").default,
  failed: require("./x-mark.png").default,
};

export default images;
