import React, { useState } from "react";
import { Redirect, useHistory } from "react-router-dom";
import { connect } from "react-redux";
import "../static/css/home/index.css";

import Header from "../components/includes/mobile_header.js";
import Desktopleft from "../components/includes/desktopleft";
import Desktopright from "../components/includes/desktopright";
import { add_wallet, logOut, loginSuc, disp_noti } from "../redux";
import { cashbackloader } from "../components/loading";
import { allCashback } from "../functions/models/index";
import Naira from "react-naira";
import List from "@mui/material/List";
import Divider from "@mui/material/Divider";
import { EuroSymbolOutlined, FileCopyOutlined } from "@material-ui/icons";
const smile = {
  color: "white",
  fontSize: "20px",
  background: "#f3f3f3",
};

function Home({ appState, dispNoti }) {
  let history = useHistory();
  const state = appState;
  let userId = "";
  var QRCode = require("qrcode.react");

  if (state.loggedIn === true) {
    userId = state.loggedInUser.user.id;
  }

  const style = {
    width: "100%",
    maxWidth: 360,
    bgcolor: "background.paper",
  };

  const [compState, setStates] = useState({
    data: [],
  });

  const setSchool = () => {
    let user = state.loggedInUser.user.id;
    setStates({
      ...compState,
      loader: true,
    });
    allCashback(user)
      .then((res) => {
        if (res.error === null) {
          setStates({
            ...compState,
            loader: false,
            data: res.body,
          });
        } else {
          setStates({
            ...compState,
            loader: false,
            data: [],
          });
        }
      })
      .catch((err) => {
        setStates({
          ...compState,
          loader: false,
          data: [],
        });
      });
  };

  React.useEffect(() => {
    window.scrollTo(0, 0);
    setSchool();
    dispNoti(false);
  }, []);

  const renderNotifications = () => {
    if (compState.data) {
      return compState.data.map((e) => {
        console.log(e);
        return (
          <>
            <div style={{ background: "" }}>
              <div
                style={{
                  backgroundColor: "",
                  width: "100%",
                  padding: "10px 20px",
                }}
              >
                <b>
                  {e.isActive === true ? (
                    <span style={{ fontSize: "12px", color: "mediumseagreen" }}>
                      🔵
                    </span>
                  ) : (
                    <span style={{ fontSize: "12px", color: "crimson" }}>
                      ⭕
                    </span>
                  )}{" "}
                </b>{" "}
                &nbsp;&nbsp;{" "}
                {e.user == userId ? (
                  <b
                    style={{
                      // color: "#0a3d62",
                      padding: "3px 10px",
                      borderRadius: "5px",
                      float: "right",
                    }}
                  >
                    <Naira>{e.meta.tokenamount}</Naira>
                    {/* <sup style={{ color: "crimson", fontSize: "13px" }}>&nbsp;<small>{e.meta.amountPlusCharge - e.meta.tokenamount}</small></sup> */}
                  </b>
                ) : (
                  <b
                    style={{
                      // color: "#0a3d62",
                      padding: "3px 10px",
                      borderRadius: "5px",
                      float: "right",
                    }}
                  >
                     {e.token}
                    {/* <sup style={{ color: "crimson", fontSize: "13px" }}>&nbsp;<small>{e.meta.amountPlusCharge - e.meta.tokenamount}</small></sup> */}
                  </b>
                )}
                <br />
                <span style={{ fontSize: "14px" }}>
                  {" "}
                  {e.meta.user.email !== state.loggedInUser.user.email ? (
                    <b style={{ fontSize: "13px" }}>
                      {" "}
                      Generated by {e.meta.name.split(" ")[0]}
                    </b>
                  ) : (
                    <b style={{ fontSize: "13px" }}> Your token</b>
                  )}
                </span>{" "}
                <br />
              </div>
              <div
                style={{
                  backgroundColor: " ",
                  width: "100%",
                  padding: "10px 20px",
                  marginTop: "-15px",
                  // borderBottom: "0.5px solid lightgray",
                }}
              >
                {e.user == userId ? (
                  <span>
                    You generated a cashback of{" "}
                    <Naira>{e.meta.tokenamount}</Naira>
                    <br />
                    <small>
                      <span style={{ color: "crimson" }}>Service charge</span>: &nbsp;
                      <div
                        style={{
                          float: "right",
                          width: "50%",
                          textAlign: "left",
                        }}
                      >
                        <Naira>
                          {e.meta.amountPlusCharge - e.meta.tokenamount}
                        </Naira>
                      </div>
                    </small>{" "}
                    <br />
                    <small>
                      <span style={{ color: "crimson" }}>Amount debited</span>:
                      &nbsp;
                      <div
                        style={{
                          float: "right",
                          width: "50%",
                          textAlign: "left",
                        }}
                      >
                        <Naira>{e.meta.amountPlusCharge}</Naira>
                      </div>
                    </small>{" "}

                    {e.isActive === false && 
                    <> <br />
                    <small>
                      <span style={{ color: "crimson" }}>Resolved by</span>:
                      &nbsp;
                      <div
                        style={{
                          float: "right",
                          width: "50%",
                          textAlign: "left",
                        }}
                      >
                        <b>{e.meta.to.fullname}</b>
                      </div>
                    </small> </>}
                    <b
                      style={{
                        // color: "#0a3d62",
                        padding: "3px 4px",
                        borderRadius: "5px",
                      }}
                    >
                      <br /> 
                    </b>
                  </span>
                ) : (
                  <small>
                    You resolved a cashback generated by {e.meta.name}
                    <br />
                    <small>
                      <span style={{ color: "mediumseagreen" }}>
                        Cashback amount
                      </span>
                      : &nbsp;
                      <div
                        style={{
                          float: "right",
                          width: "50%",
                          textAlign: "left",
                        }}
                      >
                        <Naira>{e.meta.tokenamount}</Naira>
                      </div>
                    </small>
                    <br />
                    <small>
                      <span style={{ color: "mediumseagreen" }}>Charge</span>:
                      &nbsp;
                      <div
                        style={{
                          float: "right",
                          width: "50%",
                          textAlign: "left",
                        }}
                      >
                        <Naira>{e.meta.amount - e.meta.tokenamount}</Naira>
                      </div>
                    </small>
                    <br />
                    <small>
                      <span style={{ color: "mediumseagreen" }}>
                        Amount receive
                      </span>
                      : &nbsp;
                      <div
                        style={{
                          float: "right",
                          width: "50%",
                          textAlign: "left",
                        }}
                      >
                        <Naira>{e.meta.amount}</Naira>
                      </div>
                    </small>
                    <br />
                  </small>
                )}
                {e.user == userId && (
                  <div style={{ textAlign: "center", margin: "10px 2px" }}>
                    <QRCode value={e.token} />
                    <div style={{ marginTop: "5px" }}>
                      <b style={{ fontSize: "16px", color: "#0a3d62" }}>
                        {e.token}{" "}
                      </b>
                    </div>
                  </div>
                )}
                <br />
                <small>
                  {e.meta.date.day} {e.meta.date.date} {e.meta.date.month},{" "}
                  {e.meta.date.year}
                </small>{" "}
                &nbsp;&nbsp;{" "}
                <small style={{ float: " " }}>{e.meta.date.time}</small>
              </div>
            </div>
            <Divider />
          </>
        );
      });
    }
  };
  const [copyState, setCopyState] = useState({
    status: false,
  });
  const copy = (e) => {
    setCopyState({
      ...copyState,
      status: true,
      id: e,
    });
    window.navigator.vibrate([200]);
    if (navigator && navigator.clipboard) {
      navigator.clipboard.writeText(e);
    }
    setTimeout(() => {
      setCopyState({
        ...copyState,
        status: false,
        id: "",
      });
    }, 2000);
    // setInterval(() => checkSession(logout, set_session, state), 2000);
  };

  return state.loggedIn === false ? (
    <div>
      <Redirect to="/login" />
    </div>
  ) : (
    <div id="body bg">
      <>
        {console.log(compState)}
        {compState.loader === true && <> {cashbackloader()}</>}
        <div className="mobile">
          <div>
            <div>
              {/* <div
                style={{
                  textAlign: "left",
                  marginTop: "10px",
                  background: " #f4f6f7",
                  position: "sticky",
                  top: "0px",
                  zIndex: "1000",
                  padding: "30px 20px",
                  color: "gray",
                  fontSize: "14px",
                }}
              >
                {" "}
                {compState.loader === false && compState.data.length > 0 && (
                  <b>Cashback history</b>
                )}
              </div>{" "} */}
              {compState.loader != true &&
                compState.data !== null &&
                compState.data.length > 0 && (
                  <>
                    {" "}
                    <div
                      style={{
                        // width: "90%",
                        background: "white",
                        padding: "0px",
                        // marginLeft: "5%",
                        marginTop: "20px",
                        // boxShadow: " 1px 1px 3px #888888",
                        // border: "0.5px solid #f3f3f3",
                      }}
                    >
                      <List
                        sx={style}
                        component="nav"
                        aria-label="mailbox folders"
                      >
                        {renderNotifications()}
                      </List>{" "}
                    </div>
                  </>
                )}
              <br />
              {compState.loader === false && compState.data.length == 0 && (
                <div
                  style={{
                    width: "50%",
                    background: "white",
                    padding: "10px 3px",
                    marginLeft: "25%",
                    marginTop: "20px",
                    // boxShadow: " 1px 1px 3px #888888",
                    // border: "0.5px solid #f3f3f3",
                    textAlign: "center",
                  }}
                >
                  No cashback record
                </div>
              )} 
            </div>
          </div>
        </div>

        <Desktopleft />
        <Desktopright />
      </>
    </div>
  );
}

const mapStateToProps = (state) => {
  return {
    appState: state.user,
  };
};

const mapDispatchToProps = (dispatch, encoded) => {
  return {
    walletAdd: (wallet) => dispatch(add_wallet(wallet)),
    logout: () => dispatch(logOut()),
    login_suc: (userMetadata) => dispatch(loginSuc(userMetadata)),
    dispNoti: (payload) => dispatch(disp_noti(payload)),
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(Home);
